### ISSUE TITLE
add NAME/whatis section to POD

### ISSUE THREAD

**Issue by gregoa** [shlomif/perl-pod-weaver-section-support#1]
In Debian we are currently applying the following patch to
Pod-Weaver-Section-Support.
We thought you might be interested in it too.

    Description: add NAME/whatis section to POD
     (Maybe that should have happened during release? In any case it's not there ...)
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2017-11-21
    Bug: 
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libpod-weaver-section-support-perl.git/plain/debian/patches/pod.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by shlomif** [comment]
Fixed in the 1.009 release. Thanks!

**Comment by gregoa** [comment]
On Tue, 21 Nov 2017 19:58:04 +0000, Shlomi Fish wrote:

> Fixed in the 1.009 release. Thanks!

Thanks for the quick fix, and for converting my patch into something
that actually applies against git :) 


Cheers,
gregor

-- 
 .''`.  https://info.comodo.priv.at/ - Debian Developer https://www.debian.org
 : :' : OpenPGP fingerprint D1E1 316E 93A7 60A8 104D  85FA BB3A 6801 8649 AA06
 `. `'  Member of VIBE!AT & SPI, fellow of the Free Software Foundation Europe
   `-   NP: Simon & Garfunkel: Why Don't You Write Me
