### ISSUE TITLE
Unnecessary files in CPAN distribution

### ISSUE THREAD

**Issue by dod38fr** [shlomif/perl-pod-weaver-section-support#3]
Hi

This is not a bug per se, but perl-pod-weaver-section-support tarball contains unnecessary files:
- emacs backup files (*~)
- old release file (the whole content of [releases](../tree/master/releases) directory)

This does not change the behavior of this module, but it makes downstream distribution much heavier as all these files are kept in source packages (see [libpod-weaver-section-support-perl_1.010.orig.tar.gz](http://deb.debian.org/debian/pool/main/libp/libpod-weaver-section-support-perl/libpod-weaver-section-support-perl_1.010.orig.tar.gz) )

Could you remove these files from next release ?

All the best

Dod (for Debian)

**Comment by shlomif** [comment]
should be fixed in 1.012: https://metacpan.org/recent .

**Comment by dod38fr** [comment]
That was fast ! Thanks :-)

**Comment by shlomif** [comment]
> That was fast ! Thanks :-)

you are welcome. Thanks for the headsup.
